inputs_def:
  - handle: texts
    description: Input
    json_schema:
      type: array
      items:
        type: string
    value:
      []
  - handle: llm_api
    json_schema:
      enum:
        - oomol
        - openai
        - claude
        - gemini
      ui:options:
        labels:
          - OOMOL
          - OpenAI
          - Claude
          - Gemini
    value: oomol
  - handle: key
    json_schema:
      contentMediaType: oomol/secret
      type: string
    value:
    nullable: true
  - handle: url
    json_schema:
      type: string
      minLength: 1
    value:
    nullable: true
  - handle: model
    json_schema:
      type: string
      minLength: 1
    value:
    nullable: true
  - handle: temperature
    json_schema:
      type: number
      minimum: 0
    value: 0
  - handle: timeout
    json_schema:
      type: number
      exclusiveMinimum: 0
    value:
    nullable: true
  - handle: source
    json_schema:
      enum:
        - en
        - cn
        - ja
        - fr
        - ru
        - de
      ui:options:
        labels:
          - English
          - 中文
          - 日本語
          - Français
          - Русский
          - Deutsch
    nullable: false
  - handle: target
    json_schema:
      enum:
        - en
        - cn
        - ja
        - fr
        - ru
        - de
      ui:options:
        labels:
          - English
          - 中文
          - 日本語
          - Français
          - Русский
          - Deutsch
    nullable: false
  - handle: group_max_tokens
    json_schema:
      type: integer
      exclusiveMinimum: 0
    value: 1000
outputs_def:
  - handle: texts
    description: Output
    json_schema:
      type: array
      items:
        type: string
ui:
  default_width: 508.0272091228371
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
title: Translate texts list
icon: ":twemoji:globe-with-meridians:"
